# PLANTILLA DE SECRETOS
# Copia este archivo a secrets.toml y reemplaza los valores con los reales

# API de Perplexity
PERPLEXITY_API_KEY = "tu_clave_aqui_REEMPLAZAR"

# Google Sheets
SPREADSHEET_ID = "id_de_tu_hoja_REEMPLAZAR"
RANGE_NAME = "Hoja1!A1:B1"

# Credenciales de Google Service Account
[SERVICE_ACCOUNT_JSON]
type = "service_account"
project_id = "tu-proyecto"
private_key_id = "tu_key_id"
private_key = "-----BEGIN PRIVATE KEY-----\ntu_clave_privada\n-----END PRIVATE KEY-----\n"
client_email = "tu-email@proyecto.iam.gserviceaccount.com"
client_id = "tu_client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/..."

